# Generated by Django 5.1.6 on 2025-02-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('category', models.CharField(choices=[('entertainment', 'Entertainment'), ('networking', 'Networking & Connectivity'), ('kitchenware', 'Kitchenware'), ('appliances', 'General Appliances'), ('cleaning tools', 'Cleaning'), ('accessories', 'Accessories'), ('spares', 'Electrical Spare Parts')], max_length=50)),
            ],
        ),
    ]
