# Generated by Django 5.1.6 on 2025-03-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Entertainment', 'Entertainment'), ('Networking & Connectivity', 'Networking & Connectivity'), ('Kitchenware', 'Kitchenware'), ('General Appliances', 'General Appliances'), ('Cleaning Tools', 'Cleaning'), ('Accessories', 'Accessories'), ('Electrical Spare Parts', 'Electrical Spare Parts')], max_length=50),
        ),
    ]
